development:
  adapter: postgresql
  encoding: unicode
  database: freedom_tokens_development
  pool: 5
  username: knoxjeffrey
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: freedom_tokens_test
  pool: 5
  username: knoxjeffrey
  password: 

