# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c904f813b3d60dfac543c23f2ef7f253018b12a34a79fa3cd776d58d50562e9256859cc9e0b362fcee50bc9e093f5cd6a78c8f0e3969d5f6736d075b700afad

test:
  secret_key_base: b5e056e72816fc5027e06178605ed3da25587d57d2cbd1cb5d5b5a575af0d2fe75a06b20be4fd35249d08d73336601be63c1b56bd66d430e92911d24b6654d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
